import type { DashboardRole, Rhythm } from "./types";

export const DEFAULT_PRESETS: Record<DashboardRole, Record<Rhythm, string[]>> = {
  owner: {
    today: [
      "verdict",
      "goal-vector",
      "plan-fact",
      "load",
      "stale",
      "ideas",
      "blockers",
      "feed",
      "value",
    ],
    week: [
      "verdict",
      "goal-vector",
      "trend",
      "plan-fact",
      "load",
      "stale",
      "chains",
      "blockers",
      "ideas",
      "weekly-plan-fact",
      "feed",
      "value",
    ],
    month: [
      "verdict",
      "month-recap",
      "goal-vector",
      "trend",
      "achievements",
      "weekly-dynamics",
      "maturity",
      "bus-factor",
      "plan-fact",
      "load",
      "stale",
      "chains",
      "blockers",
      "ideas",
      "weekly-plan-fact",
      "feed",
      "value",
    ],
  },
  coo: {
    today: [
      "verdict",
      "goal-vector",
      "plan-fact",
      "load",
      "stale",
      "ideas",
      "blockers",
      "feed",
      "value",
    ],
    week: [
      "verdict",
      "goal-vector",
      "trend",
      "plan-fact",
      "load",
      "stale",
      "chains",
      "blockers",
      "ideas",
      "weekly-plan-fact",
      "feed",
      "value",
    ],
    month: [
      "verdict",
      "month-recap",
      "goal-vector",
      "trend",
      "achievements",
      "weekly-dynamics",
      "maturity",
      "bus-factor",
      "plan-fact",
      "load",
      "stale",
      "chains",
      "blockers",
      "ideas",
      "weekly-plan-fact",
      "feed",
      "value",
    ],
  },
  member: {
    today: ["ideas", "value"],
    week: ["ideas", "value"],
    month: ["ideas", "value"],
  },
};

export function toDashboardRole(
  orgRole: string | null | undefined,
): DashboardRole {
  if (orgRole === "owner" || orgRole === "admin") return "owner";
  if (orgRole === "coo") return "coo";
  return "member";
}
