export type ProbeFamily =
  | 'task'
  | 'consistency'
  | 'company'
  | 'process'
  | 'insight'
  | 'experiment'
  | 'skill'
  | 'clone'
  | 'helpfulness'
  | 'attribution'
  | 'card'
  | 'goal'
  | 'temporal'
  | 'companyprofile';

export interface ProbeCatalogEntry {
  reason: string;
  service: string;
  inspector: string;
  trigger: string;
  recipient: string;
  asks: string;
  family: ProbeFamily;
  status: 'active' | 'removed';
}

export const PROBE_CATALOG: ProbeCatalogEntry[] = [
  {
    reason: 'task.assignee_unresolved',
    service: 'specialist-3-15-tasks',
    inspector: 'Specialist315TasksService.processBlock / runClarifySweep',
    trigger: 'event: извлечение задачи из блока + sweep @Cron hourly (tracker.taskClarifySweep)',
    recipient: 'постановщик (автор реплики), фолбэк owner',
    asks: 'Для кого эта задача — кому её поручить?',
    family: 'task',
    status: 'active',
  },
  {
    reason: 'task.due_date_missing',
    service: 'specialist-3-15-tasks',
    inspector: 'Specialist315TasksService.processBlock / runClarifySweep',
    trigger: 'event: извлечение задачи без срока + sweep',
    recipient: 'постановщик (автор реплики)',
    asks: 'К какому сроку нужно сделать эту задачу?',
    family: 'task',
    status: 'active',
  },
  {
    reason: 'task.poorly_specified',
    service: 'specialist-3-15-tasks',
    inspector: 'Specialist315TasksService',
    trigger: 'event: задача сформулирована нечётко',
    recipient: 'постановщик',
    asks: 'Опишите задачу подробнее / «удалить» если это не задача.',
    family: 'task',
    status: 'active',
  },
  {
    reason: 'task.method_capture',
    service: 'task-method-capture',
    inspector: 'IssuesService.transitionState → maybeRaiseMethodCaptureProbe (Ф5)',
    trigger: 'event: переход задачи в completed + complexity ≥ tracker.methodCaptureMinComplexity (0.5)',
    recipient: 'исполнитель (assignees), НЕ владелец',
    asks: 'Ты закрыл задачу «…». Расскажи пошагово, как решал (можно голосом).',
    family: 'task',
    status: 'active',
  },
  {
    reason: 'consistency_violation.R1',
    service: 'curation.consistency_checker',
    inspector: 'ConsistencyCheckerCron @Cron("0 */4 * * *")',
    trigger: 'cron каждые 4ч; dedup TTL 14400с = интервалу → перевыпуск 6×/сутки',
    recipient: 'все owner/admin Org',
    asks: 'Документ не привязан ни к одному процессу.',
    family: 'consistency',
    status: 'active',
  },
  {
    reason: 'consistency_violation.R2',
    service: 'curation.consistency_checker',
    inspector: 'ConsistencyCheckerCron @Cron("0 */4 * * *")',
    trigger: 'cron каждые 4ч; ОТДЕЛЬНЫЙ probe на КАЖДЫЙ шаг процесса',
    recipient: 'все owner/admin Org',
    asks: 'Шаг процесса не создаёт ни одного результата: «…».',
    family: 'consistency',
    status: 'active',
  },
  {
    reason: 'consistency_violation.R3',
    service: 'curation.consistency_checker',
    inspector: 'ConsistencyCheckerCron @Cron("0 */4 * * *")',
    trigger: 'cron каждые 4ч; ОТДЕЛЬНЫЙ probe на КАЖДЫЙ шаг процесса',
    recipient: 'все owner/admin Org',
    asks: 'У шага процесса не назначен ответственный: «…».',
    family: 'consistency',
    status: 'active',
  },
  {
    reason: 'consistency_violation.R4',
    service: 'curation.consistency_checker',
    inspector: 'ConsistencyCheckerCron',
    trigger: 'cron каждые 4ч',
    recipient: 'все owner/admin Org',
    asks: 'У роли есть зона ответственности без привязки к задачам.',
    family: 'consistency',
    status: 'active',
  },
  {
    reason: 'consistency_violation.R5',
    service: 'curation.consistency_checker',
    inspector: 'ConsistencyCheckerCron',
    trigger: 'cron каждые 4ч',
    recipient: 'все owner/admin Org',
    asks: 'Зона ответственности без измеримой метрики.',
    family: 'consistency',
    status: 'active',
  },
  {
    reason: 'consistency_violation.R6',
    service: 'curation.consistency_checker',
    inspector: 'ConsistencyCheckerCron',
    trigger: 'cron каждые 4ч; ДУБЛИРУЕТ company-profile-completeness',
    recipient: 'все owner/admin Org',
    asks: 'У компании не заполнены миссия, видение и стратегия.',
    family: 'consistency',
    status: 'active',
  },
  {
    reason: 'companyprofile.missing_mission',
    service: 'company-profile-completeness',
    inspector: 'company-profile-completeness cron',
    trigger: 'cron ежедневно ~04:00; ДУБЛИРУЕТ consistency R6',
    recipient: 'owner/admin',
    asks: 'Какая у компании миссия? (черновик от Коры)',
    family: 'companyprofile',
    status: 'active',
  },
  {
    reason: 'companyprofile.missing_vision',
    service: 'company-profile-completeness',
    inspector: 'company-profile-completeness cron',
    trigger: 'cron ежедневно ~04:00; ДУБЛИРУЕТ consistency R6',
    recipient: 'owner/admin',
    asks: 'Каким вы видите будущее компании?',
    family: 'companyprofile',
    status: 'active',
  },
  {
    reason: 'companyprofile.missing_strategy',
    service: 'company-profile-completeness',
    inspector: 'company-profile-completeness cron',
    trigger: 'cron ежедневно ~04:00; ДУБЛИРУЕТ consistency R6',
    recipient: 'owner/admin',
    asks: 'Какая у компании стратегия?',
    family: 'companyprofile',
    status: 'active',
  },
  {
    reason: 'process_template.missing_output_artifact',
    service: '3-1-process-detector',
    inspector: 'ProcessTemplateProbeService.checkAndEmit',
    trigger: 'event: изменение шаблона процесса',
    recipient: 'owner шаблона / owner-admin',
    asks: 'У N шагов процесса не указан результат.',
    family: 'process',
    status: 'active',
  },
  {
    reason: 'process_template.missing_input_artifact',
    service: '3-1-process-detector',
    inspector: 'ProcessTemplateProbeService.checkAndEmit',
    trigger: 'event: изменение шаблона процесса',
    recipient: 'owner шаблона / owner-admin',
    asks: 'У N шагов процесса не указан вход.',
    family: 'process',
    status: 'active',
  },
  {
    reason: 'process_template.step_without_owner',
    service: '3-1-process-detector',
    inspector: 'ProcessTemplateProbeService.checkAndEmit',
    trigger: 'event: изменение шаблона процесса',
    recipient: 'owner шаблона / owner-admin',
    asks: 'У N шагов процесса не назначен ответственный.',
    family: 'process',
    status: 'active',
  },
  {
    reason: 'insight.no_mitigation_plan',
    service: '3-5-insights',
    inspector: 'Specialist35ProbeService',
    trigger: 'event/cron: у проблемы-сигнала нет плана устранения',
    recipient: 'owner/admin',
    asks: 'Что планируете сделать, чтобы это не повторялось?',
    family: 'insight',
    status: 'active',
  },
  {
    reason: 'insight.recurring_after_mitigation',
    service: '3-5-insights',
    inspector: 'Specialist35ProbeService',
    trigger: 'event: проблема повторяется после мер',
    recipient: 'owner/admin',
    asks: 'Проблема повторяется. Что её вызывает?',
    family: 'insight',
    status: 'active',
  },
  {
    reason: 'insight.escalation_suggested',
    service: '3-5-insights',
    inspector: 'Specialist35ProbeService',
    trigger: 'event: инсайт стоит эскалировать',
    recipient: 'owner/admin',
    asks: 'Стоит ли вынести это на уровень выше?',
    family: 'insight',
    status: 'active',
  },
  {
    reason: 'experiment.no_owner',
    service: '3-9-experiments',
    inspector: 'Specialist39ExperimentProbeService',
    trigger: 'event/cron: у эксперимента нет ответственного',
    recipient: 'owner/admin',
    asks: 'Кто отвечает за этот эксперимент?',
    family: 'experiment',
    status: 'active',
  },
  {
    reason: 'experiment.result_without_lesson',
    service: '3-9-experiments',
    inspector: 'Specialist39ExperimentProbeService',
    trigger: 'event: есть результат, нет вывода',
    recipient: 'owner/admin',
    asks: 'Какой вывод вы сделали из эксперимента?',
    family: 'experiment',
    status: 'active',
  },
  {
    reason: 'experiment.running_too_long',
    service: '3-9-experiments',
    inspector: 'Specialist39ExperimentProbeService',
    trigger: 'cron: эксперимент идёт слишком долго',
    recipient: 'owner/admin',
    asks: 'Эксперимент идёт долго. Какой итог?',
    family: 'experiment',
    status: 'active',
  },
  {
    reason: 'knowledge.new_expertise_detected',
    service: '3-2-knowledge-clone',
    inspector: 'knowledge-clone-rebuild.cron @Cron("0 */6 * * *")',
    trigger: 'cron: детектор новой экспертизы человека (строит клон)',
    recipient: 'сам сотрудник',
    asks: 'Заметили у тебя новые направления. Это твои сильные стороны?',
    family: 'clone',
    status: 'active',
  },
  {
    reason: 'skill.profile_starved',
    service: '3-7-skill',
    inspector: 'Specialist37SkillProbeService',
    trigger: 'cron: мало данных о навыках',
    recipient: 'сам сотрудник',
    asks: 'Расскажете, чем вы сейчас занимаетесь?',
    family: 'skill',
    status: 'active',
  },
  {
    reason: 'skill.contradicting_traits',
    service: '3-7-skill',
    inspector: 'Specialist37SkillProbeService',
    trigger: 'cron: противоречие в профиле навыков',
    recipient: 'сам сотрудник',
    asks: 'Уточните, чем вы сейчас занимаетесь?',
    family: 'skill',
    status: 'active',
  },
  {
    reason: 'helpfulness.question_chain_unanswered',
    service: 'specialist-3-8-helpfulness',
    inspector: 'helpfulness-probe.cron @Cron("0 10 * * *")',
    trigger: 'cron: цепочка вопросов без ответа',
    recipient: 'участники',
    asks: 'Этот вопрос остался без ответа. Подскажете?',
    family: 'helpfulness',
    status: 'active',
  },
  {
    reason: 'attribution.unresolved_at_ingest',
    service: 'ingest-attribution',
    inspector: 'block-ingest.worker',
    trigger: 'event: новая сущность не привязана к отделу/клиенту',
    recipient: 'owner/admin',
    asks: 'К какому отделу, проекту или клиенту это относится?',
    family: 'attribution',
    status: 'active',
  },
  {
    reason: 'card.missing_owner',
    service: 'specialist-3-4',
    inspector: 'Specialist34ProbeService',
    trigger: 'event: у карточки нет ответственного',
    recipient: 'owner/admin',
    asks: 'Кто отвечает за это?',
    family: 'card',
    status: 'active',
  },
  {
    reason: 'temporal.fact_stale_contradiction',
    service: 'temporal-probe',
    inspector: 'temporal-probe.cron @Cron("0 7 * * 1")',
    trigger: 'cron еженедельно: факт устарел / расхождение',
    recipient: 'owner/admin',
    asks: 'Здесь расхождение в данных. Какой вариант верный?',
    family: 'temporal',
    status: 'active',
  },
  {
    reason: 'strategic_misalignment_high',
    service: 'goals/strategic-alignment-issues',
    inspector: 'goals alignment cron',
    trigger: 'cron: работа расходится со стратегией',
    recipient: 'owner/admin',
    asks: 'Как эта работа связана с вашей стратегией?',
    family: 'goal',
    status: 'active',
  },
  {
    reason: 'goal.kr_checkpoint_suggested',
    service: 'goals',
    inspector: 'goals cron',
    trigger: 'cron: пора свериться по ключевому результату',
    recipient: 'owner цели',
    asks: 'Как продвигается этот ключевой результат?',
    family: 'goal',
    status: 'active',
  },
  {
    reason: 'decision.*',
    service: 'specialist-3-3-probe (УДАЛЁН Ф1)',
    inspector: '—',
    trigger: 'снесён 2026-06-29 (overhaul Ф1)',
    recipient: '—',
    asks: 'вопросы про решения (без ответственного/просрочено/итог) — БОЛЬШЕ НЕ ШЛЮТСЯ',
    family: 'card',
    status: 'removed',
  },
  {
    reason: 'commitment.followup / commitment.silence_escalation',
    service: '3-9-promise-keeper (УДАЛЁН Ф2)',
    inspector: '—',
    trigger: 'снесён 2026-06-29 (overhaul Ф2); последний прогон в проде 30.06',
    recipient: '—',
    asks: '«Ты обещал — выполнил?» — БОЛЬШЕ НЕ ШЛЮТСЯ',
    family: 'task',
    status: 'removed',
  },
  {
    reason: 'regulation.*',
    service: 'specialist-3-1-probe (УДАЛЁН Ф7.1)',
    inspector: '—',
    trigger: 'снесён 2026-07-02 (overhaul Ф7.1); авто-назначение владельца сохранено',
    recipient: '—',
    asks: 'вопросы про регламенты (owner/шаги/актуальность) — БОЛЬШЕ НЕ ШЛЮТСЯ',
    family: 'process',
    status: 'removed',
  },
];

export function catalogByReason(reason: string): ProbeCatalogEntry | undefined {
  const exact = PROBE_CATALOG.find((e) => e.reason === reason);
  if (exact) return exact;
  const prefix = reason.split('.')[0];
  return PROBE_CATALOG.find((e) => e.reason.startsWith(`${prefix}.`) && e.status === 'active');
}
