export const PROBE_REASON_LABEL_DEFAULT = 'требуется уточнение';

export const PROBE_REASON_FALLBACK_DEFAULT = 'Можете уточнить, пожалуйста?';

export const PROBE_REASON_LABEL: Record<string, string> = {
  'decision.competing_versions': 'по решению есть конкурирующие версии',
  'decision.missing_decider': 'у решения нет ответственного за принятие',
  'decision.no_deadline_critical': 'у важного решения нет срока',
  'decision.overdue': 'решение просрочено',
  'decision.outcome_unknown': 'неизвестен итог решения',
  'decision.confirm_status': 'нужно подтвердить статус решения',
  'temporal.fact_stale_contradiction': 'факт устарел / расхождение',
  'temporal.fact_stale_contradiction.escalated': 'давнее расхождение в фактах',
  'experiment.result_without_lesson': 'у эксперимента есть результат, но нет вывода',
  'experiment.no_owner': 'у эксперимента нет ответственного',
  'experiment.running_too_long': 'эксперимент идёт слишком долго без итога',
  'knowledge.new_expertise_detected': 'замечена новая экспертиза',
  'knowledge.contradiction_detected': 'обнаружено противоречие в знаниях',
  'insight.linked_decision_question': 'инсайт связан с решением — нужен вопрос',
  'insight.escalation_suggested': 'инсайт стоит эскалировать',
  'insight.recurring_after_mitigation': 'проблема повторяется после принятых мер',
  'insight.no_mitigation_plan': 'у проблемы нет плана устранения',
  kr_checkpoint_suggested: 'пора свериться по ключевому результату',
  'goal.kr_checkpoint_suggested': 'пора свериться по ключевому результату',
  goal_alignment_low: 'задачи слабо связаны с целями',
  strategic_misalignment_high: 'работа расходится со стратегией',
  'skill.contradicting_traits': 'в профиле навыков есть противоречие',
  'skill.profile_starved': 'мало данных о навыках',
  'skill.cdm_interview': 'разбор реального кейса носителя роли',
  'regulation.missing_owner': 'у регламента нет ответственного',
  'regulation.process_no_steps': 'у процесса не описаны шаги',
  'regulation.stale': 'регламент устарел',
  'regulation.scope_unclear': 'непонятна область применения регламента',
  'card.missing_owner': 'у карточки нет ответственного',
  'card.missing_deadline': 'у карточки нет срока',
  'card.merge_suggestion': 'возможно, две карточки об одном',
  'card.outdated_summary': 'описание карточки устарело',
  'idea.support_request': 'идея ищет поддержку',
  'idea.status_unclear': 'идея зависла в обсуждении',
  'process_template.missing_input_artifact': 'у шага процесса не указан вход',
  'process_template.missing_output_artifact': 'у шага процесса не указан результат',
  'process_template.step_without_owner': 'у шага процесса нет ответственного',
  'helpfulness.new_expertise_helper_detected': 'кто-то проявил новую экспертизу, помогая',
  'helpfulness.unrecognized_high_contributor': 'активный помощник остаётся незамеченным',
  'helpfulness.mentor_emerging': 'появляется наставник',
  'helpfulness.question_chain_unanswered': 'цепочка вопросов осталась без ответа',
  'commitment.followup': 'нужно уточнить по обещанию',
  'commitment.silence_escalation': 'по обещанию давно нет ответа',
  'consistency_violation.R1': 'обнаружено расхождение в данных',
  'consistency_violation.R2': 'обнаружено расхождение в данных',
  'consistency_violation.R3': 'обнаружено расхождение в данных',
  'consistency_violation.R4': 'обнаружено расхождение в данных',
  'consistency_violation.R5': 'обнаружено расхождение в данных',
  'consistency_violation.R6': 'обнаружено расхождение в данных',
  // attribution.* (Ф6 2026-06-17 — ingest-повод атрибуции новой сущности)
  'attribution.unresolved_at_ingest':
    'новая сущность не привязана к отделу/клиенту',
  'task.assignee_unresolved': 'у задачи не определён исполнитель',
  'task.due_date_missing': 'у задачи не указан срок',
  'task.poorly_specified': 'задача сформулирована нечётко',
  'task.false_positive': 'возможно, это не задача',
  'task.completion_detail_missing': 'не хватает деталей о выполнении',
  'companyprofile.missing_mission': 'Миссия компании не задана',
  'companyprofile.missing_vision': 'Видение компании не задано',
  'companyprofile.missing_strategy': 'Стратегия компании не задана',
};

export const PROBE_REASON_FALLBACK: Record<string, string> = {
  'decision.competing_versions': 'По этому решению есть несколько версий — какая актуальная?',
  'decision.missing_decider': 'Кто отвечает за это решение?',
  'decision.no_deadline_critical': 'К какому сроку нужно принять это решение?',
  'decision.overdue': 'Это решение должно было исполниться. На каком оно сейчас этапе?',
  'decision.outcome_unknown': 'Чем в итоге закончилось это решение?',
  'decision.confirm_status': 'Какой сейчас статус у этого решения?',
  'temporal.fact_stale_contradiction': 'Здесь есть расхождение в данных. Какой вариант верный?',
  'temporal.fact_stale_contradiction.escalated':
    'Это расхождение давно не разрешено. Какой вариант актуальный?',
  'experiment.result_without_lesson': 'Какой вывод вы сделали из этого эксперимента?',
  'experiment.no_owner': 'Кто отвечает за этот эксперимент?',
  'experiment.running_too_long': 'Этот эксперимент идёт уже долго. Какой по нему итог?',
  'knowledge.new_expertise_detected': 'Заметили, что вы разбираетесь в этой теме. Так и есть?',
  'knowledge.contradiction_detected': 'Здесь есть противоречие. Как на самом деле?',
  'insight.escalation_suggested': 'Стоит ли вынести это на уровень выше?',
  'insight.recurring_after_mitigation': 'Проблема повторяется. Что, по-вашему, её вызывает?',
  'insight.no_mitigation_plan': 'Что планируете сделать, чтобы это не повторялось?',
  kr_checkpoint_suggested: 'Как продвигается этот ключевой результат?',
  'goal.kr_checkpoint_suggested': 'Как продвигается этот ключевой результат?',
  goal_alignment_low: 'Эти задачи связаны с какой-то из целей?',
  strategic_misalignment_high: 'Как эта работа связана с вашей стратегией?',
  'skill.profile_starved': 'Расскажете, чем вы сейчас занимаетесь?',
  'skill.contradicting_traits': 'Уточните, пожалуйста, чем вы сейчас занимаетесь?',
  'skill.cdm_interview':
    'Расскажите про недавний рабочий случай, где пришлось выбирать: почему выбрали именно этот вариант и какие альтернативы отвергли?',
  'regulation.missing_owner': 'Кто отвечает за этот регламент?',
  'regulation.process_no_steps': 'Из каких шагов состоит этот процесс?',
  'regulation.stale': 'Этот регламент ещё актуален или его пора обновить?',
  'regulation.scope_unclear': 'На кого и на какие случаи распространяется этот регламент?',
  'card.missing_owner': 'Кто отвечает за это?',
  'card.missing_deadline': 'К какому сроку это нужно сделать?',
  'card.merge_suggestion': 'Возможно, это об одном и том же. Объединить?',
  'card.outdated_summary': 'Это описание ещё актуально?',
  'idea.support_request': 'Поддержите эту идею или у вас есть сомнения?',
  'idea.status_unclear': 'Эта идея давно обсуждается. К чему в итоге пришли?',
  'process_template.step_without_owner': 'Кто отвечает за этот шаг процесса?',
  'helpfulness.question_chain_unanswered': 'Этот вопрос так и остался без ответа. Подскажете?',
  'commitment.followup': 'Как продвигается то, что вы обещали?',
  'commitment.silence_escalation': 'По вашему обещанию давно нет новостей. Как с ним сейчас?',
  'attribution.unresolved_at_ingest':
    'К какому отделу, проекту или клиенту это относится?',
  'task.assignee_unresolved': 'Для кого эта задача — кому её поручить?',
  'task.due_date_missing': 'К какому сроку нужно сделать эту задачу?',
  'task.poorly_specified':
    'Опишите задачу подробнее: что конкретно нужно сделать? Если это не задача — ответьте «удалить».',
  'task.false_positive':
    'Похоже, это не задача. Удалить её? Ответьте «удалить», либо уточните, в чём суть.',
  'insight.linked_decision_question':
    'Этот инсайт связан с решением. Что предлагаете с ним сделать?',
  'process_template.missing_input_artifact':
    'Что нужно на входе этого шага процесса?',
  'process_template.missing_output_artifact':
    'Какой результат должен давать этот шаг процесса?',
  'helpfulness.new_expertise_helper_detected':
    'Заметили, что вы помогли коллеге в этой теме. Это ваша зона экспертизы?',
  'helpfulness.unrecognized_high_contributor':
    'Вы часто помогаете команде. В чём вам легче всего помогать?',
  'helpfulness.mentor_emerging':
    'Похоже, к вам обращаются за советом. По каким темам?',
  'consistency_violation.R1': 'Здесь есть расхождение в данных. Какой вариант верный?',
  'consistency_violation.R2': 'Здесь есть расхождение в данных. Какой вариант верный?',
  'consistency_violation.R3': 'Здесь есть расхождение в данных. Какой вариант верный?',
  'consistency_violation.R4': 'Здесь есть расхождение в данных. Какой вариант верный?',
  'consistency_violation.R5': 'Здесь есть расхождение в данных. Какой вариант верный?',
  'consistency_violation.R6': 'Здесь есть расхождение в данных. Какой вариант верный?',
  'task.completion_detail_missing': 'Что конкретно вы сделали с этой задачей?',
  'companyprofile.missing_mission':
    'Какая у компании миссия? Кора набросала черновик из ваших решений — проверьте и поправьте.',
  'companyprofile.missing_vision':
    'Каким вы видите будущее компании? Кора набросала черновик из ваших решений — проверьте и поправьте.',
  'companyprofile.missing_strategy':
    'Какая у компании стратегия? Кора набросала черновик из ваших решений — проверьте и поправьте.',
};
