import type { TourDefinition } from "../types";
import { NAV_HELP } from "@/lib/nav-help";

function help(navKey: string) {
  return NAV_HELP[navKey] ?? { title: navKey, body: "" };
}

export const overviewTour: TourDefinition = {
  id: "overview",
  steps: [
    {
      id: "intro",
      target: "center",
      title: "Покажу за минуту, что где лежит",
      body: "Несколько коротких подсказок по разделам. Можно листать кнопкой «Дальше» или закрыть крестиком — все эти подсказки потом всегда доступны при наведении на любой пункт меню.",
      placement: "center",
      primaryAction: { label: "Поехали", kind: "next" },
      secondaryAction: { label: "Пропустить", kind: "skip" },
    },
    {
      id: "logo",
      target: '[data-overview-target="overview.logo"]',
      title: help("/dashboard").title,
      body: "Логотип Коры — кликните, чтобы вернуться на «Сегодня» из любого раздела.",
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "org-switcher",
      target: '[data-overview-target="overview.org-switcher"]',
      title: "Переключатель компании",
      body: "Если у вас несколько компаний — переключайтесь между ними здесь.",
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "create",
      target: '[data-overview-target="overview.create"]',
      title: "Создать",
      body: "Один вход для всего: встреча, мысль (быстрая заметка в память), задача, цель.",
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "dashboard",
      target: '[data-overview-target="overview.dashboard"]',
      title: help("/dashboard").title,
      body: help("/dashboard").body,
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "week",
      target: '[data-overview-target="overview.week"]',
      title: help("/week").title,
      body: help("/week").body,
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "month",
      target: '[data-overview-target="overview.month"]',
      title: help("/month").title,
      body: help("/month").body,
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "meetings",
      target: '[data-overview-target="overview.meetings"]',
      title: help("/meetings").title,
      body: help("/meetings").body,
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "projects",
      target: '[data-overview-target="overview.projects"]',
      title: help("/projects").title,
      body: help("/projects").body,
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "memory",
      target: '[data-overview-target="overview.memory"]',
      title: help("/memory").title,
      body: help("/memory").body,
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "team",
      target: '[data-overview-target="overview.team"]',
      title: help("/structure").title,
      body: help("/structure").body,
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "me",
      target: '[data-overview-target="overview.me"]',
      title: help("/me").title,
      body: help("/me").body,
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "settings",
      target: '[data-overview-target="overview.settings"]',
      title: help("/settings").title,
      body: help("/settings").body,
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "admin",
      target: '[data-overview-target="overview.admin"]',
      title: help("/company-admin").title,
      body: help("/company-admin").body,
      placement: "right",
      primaryAction: { label: "Дальше", kind: "next" },
    },
    {
      id: "concierge",
      target: '[data-tour-target="welcome.concierge"]',
      title: help("concierge").title,
      body: help("concierge").body,
      placement: "left",
      primaryAction: { label: "Готово", kind: "complete" },
    },
  ],
};
